---
- name: Pulling Application Image
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Pull DockerHub Image
      docker_image:
        name: 'sohamjoshi/devops_calculator'
        source: pull
      vars:
        - ansible_python_interpreter: /bin/python3