---
- name: Pulling Application Image
  hosts: all
  tasks:
    - name: Pull DockerHub Image
      docker_image:
        name: 'sohamjoshi/devops_calculator'
        source: pull
      vars:
        - ansible_python_interpreter: /usr/bin/python3
        - ansible_user: soham
        - ansible_connection: ssh
        - ansible_ssh_user: soham

